<?php

use Productreview\Reviews\Block\ProductReviewCodeSnippets;
use Productreview\Reviews\Model\Settings;

/* @var $block ProductReviewCodeSnippets */

if (!$block->isModuleActive()) return;

$settings = $block->getSettings();

switch ($block->getData('section')) {
    case 'product':
        if ($settings->getProductPageInlineRating() !== Settings::PRODUCT_PAGE_INLINE_RATING_ENABLED) return;

        break;
    case 'category':
        if ($settings->getCategoryPageInlineRating() !== Settings::CATEGORY_PAGE_INLINE_RATING_ENABLED) return;

        break;
    default:
        return;
}

echo $block::inlineRating($block->findCurrentProduct()->getId(), $block->getData('section'));
